spring:
  application:
   name: faturamento
  kafka:
    bootstrap-server: 'http://localhost:29092'
    consumer:
      group-id: icompras-faturamento
      auto-offset-reset: earliest

icompras:
  config:
    kafka:
      topics:
        pedidos-pagos: 'icompras.pedidos-pagos'
server:
  port: 8083

  
minio:
  url: 'htpp://localhost:9000'
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: icompras.faturas
